name       : synfigstudio
version    : 1.4.0
release    : 20
source     :
    - https://github.com/synfig/synfig/releases/download/v1.4.0/synfigstudio-1.4.0.tar.gz : ca1eb1a3e2264c57974a576d1995e005079d96cee19d3dffaacded72c93fbd56
license    : GPL-3.0-or-later
component  : multimedia.video
homepage   : https://www.synfig.org/
summary    : Create and edit 2D animations and compositions
description: |
    Synfig Studio is a free and open-source 2D animation software, designed as powerful industrial-strength solution for creating film-quality animation using a vector and bitmap artwork. It eliminates the need to create animation frame-by frame, allowing you to produce 2D animation of a higher quality with fewer people and resources.
builddeps  :
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(synfig)
setup      : |
    %configure --disable-update-mimedb
build      : |
    %make
install    : |
    %make_install
