name       : synfigstudio
version    : 1.2.2
release    : 12
source     :
    - https://github.com/synfig/synfig/releases/download/v1.2.2/source-synfigstudio-1.2.2.tar.gz : 76fa37998af634cf694f9b5bdfcb90220bc88f8527df117d9282a39fe01489e2
license    : GPL-3.0-or-later
component  : multimedia.video
summary    : Vector based 2D animation package
description: |
    Synfig is a vector based 2D animation package. It is designed to be capable of producing feature-film quality animation. It eliminates the need for tweening, preventing the need to hand-draw each frame.
builddeps  :
    - pkgconfig(ETL)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(ImageMagick)
    - pkgconfig(sigc++-2.0)
    - pkgconfig(synfig)
rundeps    :
    - imagemagick
setup      : |
    %configure --disable-update-mimedb
build      : |
    %make
install    : |
    %make_install