name       : synfigstudio
version    : 1.5.1
release    : 26
source     :
    - https://github.com/synfig/synfig/releases/download/v1.5.1/synfigstudio-1.5.1.tar.gz : 54589b83cf7e8fd5c6aee78141b564f301a7a3b0c5fa61aec6e703860d42bf5b
license    : GPL-3.0-or-later
component  : multimedia.video
homepage   : https://www.synfig.org/
summary    : Create and edit 2D animations and compositions
description: |
    Synfig Studio is a free and open-source 2D animation software, designed as powerful industrial-strength solution for creating film-quality animation using a vector and bitmap artwork. It eliminates the need to create animation frame-by frame, allowing you to produce 2D animation of a higher quality with fewer people and resources.
builddeps  :
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(synfig)
setup      : |
    %configure --disable-update-mimedb
build      : |
    %make
install    : |
    %make_install
