name       : synfigstudio
version    : 1.0.2
release    : 3
source     :
    - http://internode.dl.sourceforge.net/project/synfig/releases/1.0.2/source/synfigstudio-1.0.2.tar.gz : e44584aa0b561f374edcfb792eb601083c7e7e111d68d6fe0356def9682347f5
license    : GPL-3.0
component  : multimedia.video
summary    : Vector based 2D animation package
description: |
    Synfig is a vector based 2D animation package. It is designed to be capable of producing feature-film quality animation. It eliminates the need for tweening, preventing the need to hand-draw each frame.
builddeps  :
    - pkgconfig(ETL)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(ImageMagick)
    - pkgconfig(sigc++-2.0)
    - pkgconfig(synfig)
rundeps    :
    - imagemagick
setup      : |
    %patch -p1 < $pkgfiles/Fix-sigcpp-includes.patch
    %configure
build      : |
    %make
install    : |
    %make_install
