name       : synfigstudio
version    : 1.2.0
release    : 5
source     :
    - https://jaist.dl.sourceforge.net/project/synfig/releases/1.2.0/source/synfigstudio-1.2.0.tar.gz : 159b6bef1f5a819602f82014f787c22d4c9108af749fcd4505ee37c4979b6c39
license    : GPL-3.0
component  : multimedia.video
summary    : Vector based 2D animation package
description: |
    Synfig is a vector based 2D animation package. It is designed to be capable of producing feature-film quality animation. It eliminates the need for tweening, preventing the need to hand-draw each frame.
builddeps  :
    - pkgconfig(ETL)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(ImageMagick)
    - pkgconfig(sigc++-2.0)
    - pkgconfig(synfig)
rundeps    :
    - imagemagick
setup      : |
    #%patch -p1 < $pkgfiles/Fix-sigcpp-includes.patch
    %configure
build      : |
    %make
install    : |
    %make_install
